{
    "docs": "https://docs.ansible.com/ansible-core/2.13/dev_guide/testing/sanity/import.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test import --python 3.10` [[explain](https://docs.ansible.com/ansible-core/2.13/dev_guide/testing/sanity/import.html)] failed with 6 errors:", 
            "output": "plugins/cliconf/ix.py:33:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'\nplugins/module_utils/network/ix/facts/facts.py:5:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'\nplugins/module_utils/network/ix/ix.py:35:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'\nplugins/modules/ix_command.py:106:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'\nplugins/modules/ix_config.py:104:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'\nplugins/terminal/ix.py:10:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'"
        }
    ], 
    "verified": false
}
